name: Test

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'

permissions:
  contents: read

env:
  GOOGLE_PROJECT: ${{ vars.GOOGLE_PROJECT }}
  GOOGLE_REGION: ${{ vars.GOOGLE_REGION }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - run: terraform fmt -check

      - run: terraform init && terraform validate

  test:
    runs-on: ubuntu-latest
    permissions:
      # NOTE: GitHub Actions doesn't allow step-level permissions
      id-token: write # google-github-actions/auth
    env:
      TF_INPUT: false
    steps:
      - uses: actions/checkout@v5

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - uses: google-github-actions/auth@v3
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          workload_identity_provider: projects/${{ vars.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-oidc/providers/github-oidc

      - name: Test alert policies
        run: terraform init && terraform test
        working-directory: ./modules/alert-policies
